- name: "Set allow-user-extension-installations '{{ value }}'"
  ansible.builtin.include_tasks: func/lock_bool_setting.yml
  vars:
    description: "allow-user-extension-installations"
    setting: "xpinstall.enabled"
    value: "{{ 'true' if allow_user_extension_install else 'false' }}"

- name: "Set enable-pocket-feature '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable Pocket feature"
    setting: "browser.pocket.enabled"
    value: "{{ 'true' if enable_pocket_extension else 'false' }}"

- name: "Set enable-pocket-extension '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable Pocket extension"
    setting: "extensions.pocket.enabled"
    value: "{{ 'true' if enable_pocket_extension else 'false' }}"

- name: "Set enable-pocket-in-menu-page '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable Pocket in menu-page"
    setting: "browser.newtabpage.activity-stream.feeds.section.topstories"
    value: "{{ 'true' if enable_pocket_extension else 'false' }}"

- name: "Set install-google-widevine-drm-add-on '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "install google-widevine drm add-on"
    setting: "media.eme.enabled"
    value: "{{ 'true' if install_google_widevine_drm_addon else 'false' }}"

- name: "Configure the vimium extension"
  ansible.builtin.include_role:
    name: ans_role_config_vimium
  vars:
    vimium_search_providers: "{{ firefox_search_providers }}"
    vimium_config_file_path: "{{ os_vimium_config_file_path }}"
    vimium_home_page: "{{ home_page }}"
  when: install_vimium_ext

