- name: "Create firefox settings-redirect file 'local-settings.js'"
  ansible.builtin.template:
    dest: "{{ os_redirect_file_path }}"
    src: 'local-settings.j2'
    owner: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

- name: "Create system-wide firefox policies directory, if not exist"
  ansible.builtin.file:
    path: "{{ os_policies_file_path | dirname }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

