- name: "Initialize extension-install entries list"
  ansible.builtin.set_fact:
    ext_list: []

- name: "Add each option extension to the entries list"
  ansible.builtin.include_tasks: entries.yml

- name: "Construct extension-install-entries-string from the entries list"
  ansible.builtin.set_fact:
    ext_install_entries: "{{ ext_list | join() | indent(width=6, first=false) }}"

- name: "Create system-wide firefox policies directory, if not exist"
  ansible.builtin.file:
    path: "{{ os_policies_file_path | dirname }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

- name: "Create firefox 'policies.json' settings file, with extension-install list"
  ansible.builtin.template:
    dest: "{{ os_policies_file_path }}"
    src: 'policies.j2'
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

- name: "Configure the vimium extension"
  ansible.builtin.include_role:
    name: ans_role_config_vimium
  vars:
    vimium_search_providers: "{{ firefox_search_providers }}"
    vimium_config_file_path: "{{ os_vimium_config_file_path }}"
    vimium_home_page: "{{ home_page }}"
  when: install_vimium_ext

