- name: "Create system-wide firefox settings directory, if not exist"
  ansible.builtin.file:
    path: "{{ firefox_sys_settings_file_path | dirname }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

- name: "Create system-wide firefox settings file '{{ firefox_sys_settings_file_path }}'"
  ansible.builtin.template:
    dest: "{{ firefox_sys_settings_file_path }}"
    src: 'mozilla_cfg.j2'
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

- name: "Create system-wide firefox settings-redirect directory, if not exist"
  ansible.builtin.file:
    path: "{{ firefox_sys_redirect_file_path | dirname }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

- name: "Create system-wide firefox settings-redirect file '{{ firefox_sys_redirect_file_path }}'"
  ansible.builtin.template:
    dest: "{{ firefox_sys_redirect_file_path }}"
    src: 'local-settings_js.j2'
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

