- name: "Set the home page to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_string_setting.yml
  vars:
    description: "home page url"
    setting: "browser.startup.homepage"
    value: "{{ home_page }}"

- name: "Set show-default-menu in new tab page to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "show default menu in new tab"
    setting: "browser.newtabpage.enabled"
    value: "{{ 'true' if show_menu_page_in_new_tab else 'false' }}"

- name: "Set hide-http in url bar to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "hide 'http://' in url bar"
    setting: "browser.urlbar.trimURLs"
    value: "{{ 'true' if hide_http_in_url_bar else 'false' }}"

- name: "Set guess-domain-names to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "guess domain names"
    setting: "browser.fixup.alternate.enabled"
    value: "{{ 'true' if guess_domain_names else 'false' }}"

- name: "Set enable-auto-extension-updates to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "update extensions automatically"
    setting: "extensions.update.enabled"
    value: "{{ 'true' if auto_update_extensions else 'false' }}"

- name: "Set enable-system-addon-updates to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "update system-addons automatically"
    setting: "extensions.systemAddon.update.enabled"
    value: "{{ 'true' if auto_update_system_addons else 'false' }}"

- name: "Set enable-extension-recommendation to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "recommend extensions"
    setting: "browser.discovery.enabled"
    value: "{{ 'true' if recommend_extensions else 'false' }}"

- name: "Set enable-menu-page-extension-recommendation to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "recommend menu-page extensions"
    setting: "browser.newtabpage.activity-stream.asrouter.userprefs.cfr"
    value: "{{ 'true' if recommend_extensions else 'false' }}"

- name: "Set app-crash-report-url to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_string_setting.yml
  vars:
    description: "application crash-report url"
    setting: "breakpad.reportURL"
    value: "{{ 'https://crash-stats.mozilla.org/report/index/' if send_app_crash_reports else '' }}"

- name: "Set send-browser-tab-crash-reports to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "send browser-tab crash reports"
    setting: "browser.tabs.crashReporting.sendReport"
    value: "{{ 'true' if send_browser_tab_crash_reports else 'false' }}"

- name: "Set show-crash-report-dialog to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "show crash-report dialog"
    setting: "browser.crashReports.unsubmittedCheck.enabled"
    value: "{{ 'true' if show_crash_report_dialog else 'false' }}"

