- name: "Set allow-user-extension-installations '{{ value }}'"
  ansible.builtin.include_tasks: func/lock_bool_setting.yml
  vars:
    description: "allow-user-extension-installations"
    setting: "xpinstall.enabled"
    value: "{{ 'true' if allow_user_extension_install else 'false' }}"

- name: "Set enable-pocket-feature '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable Pocket feature"
    setting: "browser.pocket.enabled"
    value: "{{ 'true' if enable_pocket_extension else 'false' }}"

- name: "Set enable-pocket-extension '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable Pocket extension"
    setting: "extensions.pocket.enabled"
    value: "{{ 'true' if enable_pocket_extension else 'false' }}"

- name: "Set enable-pocket-in-menu-page '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable Pocket in menu-page"
    setting: "browser.newtabpage.activity-stream.feeds.section.topstories"
    value: "{{ 'true' if enable_pocket_extension else 'false' }}"

- name: "Set install-google-widevine-drm-add-on '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "install google-widevine drm add-on"
    setting: "media.eme.enabled"
    value: "{{ 'true' if install_google_widevine_drm_addon else 'false' }}"

- name: "Emplace settings file for tridactyl extension"
  block:
    - name: "Create tridactyl config dir at {{ settings_file_path | dirname }}"
      ansible.builtin.file:
        path: "{{ settings_file_path | dirname }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '755'
    - name: "Add custom tridactyl settings file at '{{ settings_file_path }}'"
      ansible.builtin.template:
        dest: "{{ settings_file_path }}"
        src: 'tridactylrc.j2'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '644'
        force: yes
  vars:
    settings_file_path: "/home/{{ user_name }}/.config/tridactyl/tridactylrc"
  become: true
  become_user: root
  when: install_tridactyl_ext

