- name: "Set show-menu-page in new tab page to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "show default menu in new tab"
    setting: "browser.newtabpage.enabled"
    value: "{{ 'true' if show_menu_page_in_new_tab else 'false' }}"

- name: "Set download-mozilla-news for menu-page to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "download mozilla news for new-tab-default-menu"
    setting: "browser.aboutHomeSnippets.updateUrl"
    value: "{{ 'true' if show_mozilla_news_in_menu_page else 'false' }}"

- name: "Set show-mozilla-news in menu-page to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "show mozilla news in new-tab-default-menu"
    setting: "browser.newtabpage.activity-stream.feeds.snippets"
    value: "{{ 'true' if show_mozilla_news_in_menu_page else 'false' }}"

- name: "Set enable-menu-page-extension-recommendation to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "recommend menu-page extensions"
    setting: "browser.newtabpage.activity-stream.asrouter.userprefs.cfr"
    value: "{{ 'true' if recommend_extensions else 'false' }}"

- name: "Set show-menu-page-highlight-row to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "show menu-page highlight-row"
    setting: "browser.newtabpage.activity-stream.feeds.section.highlights"
    value: "{{ 'true' if show_page else 'false' }}"
    show_page: "{{ show_visited_pages_in_menu_page_highlight_row or
                   show_bookmarks_in_menu_page_highlight_row or
                   show_downloads_in_menu_page_highlight_row }}"

