- name: "Set enable-built-in-password-manager to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "enable built-in password manager"
    setting: "signon.rememberSignons"
    value: "{{ 'true' if enable_password_manager else 'false' }}"

- name: "Set save-user-form-data to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "save user form data"
    setting: "browser.formfill.enable"
    value: "{{ 'true' if save_user_form_data else 'false' }}"

- name: "Set auto-fill-form-data to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "auto-fill form data"
    setting: "signon.autofillForms"
    value: "{{ 'true' if auto_fill_form_data else 'false' }}"

- name: "Set app-crash-report-url to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_string_setting.yml
  vars:
    description: "application crash-report url"
    setting: "breakpad.reportURL"
    value: "{{ 'https://crash-stats.mozilla.org/report/index/' if send_app_crash_reports else '' }}"

- name: "Set send-browser-tab-crash-reports to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "send browser-tab crash reports"
    setting: "browser.tabs.crashReporting.sendReport"
    value: "{{ 'true' if send_browser_tab_crash_reports else 'false' }}"

- name: "Set show-crash-report-dialog to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "show crash-report dialog"
    setting: "browser.crashReports.unsubmittedCheck.enabled"
    value: "{{ 'true' if show_crash_report_dialog else 'false' }}"

- name: "Set enable-extension-recommendation to '{{ value }}'"
  ansible.builtin.include_tasks: func/edit_bool_setting.yml
  vars:
    description: "recommend extensions"
    setting: "browser.discovery.enabled"
    value: "{{ 'true' if recommend_extensions else 'false' }}"

- name: "Set use-dns-over-https to '{{ 'true' if use_dns_over_https else 'false' }}'"
  ansible.builtin.include_tasks: func/edit_numeric_setting.yml
  vars:
    description: "use-dns-over-https"
    setting: "network.trr.mode"
    value: "{{ 2 if use_dns_over_https else 5 }}"

