- ansible.builtin.include_tasks: privacy_settings.yml

- ansible.builtin.include_tasks: general_ui_settings.yml

- ansible.builtin.include_tasks: menu_page_ui_settings.yml

- ansible.builtin.include_tasks: update_settings.yml

- ansible.builtin.include_tasks: extension_settings.yml

