- name: "Install main 'firefox' package"
  community.general.pacman:
    name: firefox
    state: present
  become: true
  become_user: root

- name: "Install official Firefox browser extensions"
  ansible.builtin.include_tasks: official_ext.yml

