# url to show when "home" button is clicked
# set to 'about:home' to show the firefox menu-page
home_page: 'https://www.google.com'

# hide 'http://' and single trailing '/' in url-bar
hide_http_in_url_bar: false

# guess 'www.mozilla.com' if 'mozilla' entered in url-bar
guess_domain_names: false

# show live/debounced search suggestions during typing in search-bar or url-bar
show_live_search_suggestions: true

# show the "other" section in bookmarks
show_other_bookmarks_section: false

# show privacy, getting-started, etc pages on the first-run of firefox browser
show_first_run_pages: true

