# send application crash reports to mozilla crash-report server
send_app_crash_reports: false

# send browser-tab crash reports to mozilla servers
send_browser_tab_crash_reports: false

# query user with crash-report dialog
show_crash_report_dialog: false

# recommend/suggest related extensions (in the menu-page, and elsewhere)
recommend_extensions: false

# use dns-over-https feature (2020-04: mozilla still uses cloudflare for this)
use_dns_over_https: false

