# show live/debounced search suggestions during typing in search-bar or url-bar
show_live_search_suggestions: true

# show url-bar inline autocomplete (show/highlight matched url after typed text)
show_urlbar_inline_autocomplete: true

