# url to show when "home" button is clicked ('about:home' for firefox menu-page)
home_page: 'https://www.google.com'

# show the firefox menu-page on opening new tab (if false, show blank page)
show_menu_page_in_new_tab: false

# hide 'http://' and single trailing '/' in url bar
hide_http_in_url_bar: false

# guess 'www.mozilla.com' if 'mozilla' entered in url bar
guess_domain_names: false

# update installed extensions automatically
auto_update_extensions: false

# update firefox 'system' add-ons automatically
# warning: these add-ons can be 'critical' - Arch Linux enables this by default
auto_update_system_addons: true

