# url to show when "home" button is clicked
# set to 'about:home' to show the firefox menu-page
home_page: 'https://www.google.com'

# show the firefox menu-page on opening new tab (if false, show blank page)
show_menu_page_in_new_tab: false

# hide 'http://' and single trailing '/' in url-bar
hide_http_in_url_bar: false

# guess 'www.mozilla.com' if 'mozilla' entered in url-bar
guess_domain_names: false

# show live/debounced search suggestions during typing in search-bar or url-bar
show_live_search_suggestions: true

